services:
  web:
    build: .
    ports:
      - "5001:5000"
    environment:
      - FLASK_ENV=development
      - DATABASE_URL=mysql+mysqlconnector://root:password@db/students
    depends_on:
      db:
        condition: service_healthy
    command: sh -c "sleep 10 && python app.py"

  db:
    image: mysql:8.0.39
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: students
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 5s
      retries: 10

volumes:
  mysql_data: